version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt
      - pip install aws-sam-cli

  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests -v

  build:
    commands:
      - sam build -t devops/template.yml

  post_build:
  commands:
    - echo Packaging SAM application...
    - sam package --template-file .aws-sam/build/template.yaml --s3-bucket user-register-pipeline-artifacts --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml