version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.13

    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo Running unit tests...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests -v

  build:
    commands:
      - echo Building SAM application...
      - sam build -t devops/template.yaml

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - .aws-sam/build/template.yaml
    - .aws-sam/build/**/*